services:

  mssqlserver:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: mssqlserver
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=msSQL@123
    ports:
        - '1433:1433'
    networks:
      - nhibernateApp

networks:
  nhibernateApp:
    driver: bridge